---
apiVersion: v1
kind: Service
metadata:
  name: nanaproxy-static-service
  labels:
    app: nanaproxy-static-service
spec:
  ports:
    - port: 15020
      name: http
  selector:
    app: nanaproxy-static
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nanaproxy-static
  labels:
    app: nanaproxy-static
    version: v1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nanaproxy-static
  template:
    metadata:
      labels:
        hskp.io/component: springboot
        app: nanaproxy-static
        version: v1
      annotations:
        sidecar.istio.io/inject: "false"
        prometheus.io/path: /stats/prometheus
        prometheus.io/port: "15020"
        prometheus.io/scrape: "true"
    spec:
      containers:
      - name: app
        image: harbor.open.hand-china.com/hskp/nanoproxy-static:0.1.0
        imagePullPolicy: Always
        args:
        - --port
        - "15020"
        - --target
        - 172.23.16.213:30654
        - --verbose
        ports:
        - containerPort: 15020
---